import { GoogleGenAI } from "@google/genai";
import { localToonify, localRemoveBackground } from './localAiService';

// Preference for Local vs Cloud AI
let useLocalAi = true;

const DEFAULT_GEMINI_API_KEY = "AIzaSyBpAF_Vcc41aIoW1PVljNfwwz2-en8OdcE";

export const getUserApiKey = () => {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('user_gemini_api_key') || DEFAULT_GEMINI_API_KEY;
  }
  return DEFAULT_GEMINI_API_KEY;
};

export function setAiEngine(useLocal: boolean) {
  useLocalAi = useLocal;
}

export function getAiEngine() {
  return useLocalAi;
}

export async function transformImage(base64Image: string, stylePrompt: string, mimeType: string = "image/png", styleId: string = "classic-toon") {
  if (useLocalAi) {
    console.log("Using Local AI Engine for transformation...");
    return await localToonify(base64Image, styleId);
  }

  const apiKey = getUserApiKey() || (process.env as any).GEMINI_API_KEY || "";
  if (!apiKey) {
    throw new Error("No Gemini API key found for Pro transformation. Please add your key in the Profile settings.");
  }

  const ai = new GoogleGenAI({ apiKey });
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          {
            text: `[CRITICAL: MANDATORY IMAGE OUTPUT] You are an AI artistic transformation engine.
INPUT: An image and a style/instruction.
TASK: Transform the input image into the style: ${stylePrompt}.
ARTISTIC GUIDELINES: ${stylePrompt}
RESPONSE RULE: Return ONLY the transformed image data. NO TEXT. NO EXPLANATIONS. NO MARKDOWN. ONLY THE IMAGE.`
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Image.split(',')[1] || base64Image
            }
          }
        ]
      },
      config: {
        temperature: 0.1,
        topP: 0.8,
        topK: 10
      }
    });

    const candidates = response.candidates || [];
    const firstCandidate = candidates[0];
    if (firstCandidate?.content?.parts) {
      for (const part of firstCandidate.content.parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    
    // If we get here, no image was returned. Check if there's text.
    const responseText = response.candidates?.[0]?.content?.parts?.map(p => p.text).join(' ') || "";
    if (responseText) {
      console.log("Gemini 2.5 Artistry Response (Text Only):", responseText);
      const lowerText = responseText.toLowerCase();
      if (lowerText.includes("quota") || lowerText.includes("limit") || lowerText.includes("capacity")) {
        throw new Error("Pro AI quota exceeded. Please switch to LITE mode or try again later.");
      }
      if (lowerText.includes("safety") || lowerText.includes("policy")) {
        throw new Error("AI Transformation blocked by safety filters. Please try a different image.");
      }
      throw new Error("No image generated by the model. The AI returned text instructions instead of an artistic result. Please try a different style or use LITE mode.");
    }

    throw new Error("No image generated by the model.");
  } catch (error: any) {
    console.error("Image transformation failed:", error);
    
    // Check for quota exceeded error
    const errorMessage = error.message || String(error);
    if (errorMessage.toLowerCase().includes("quota") || errorMessage.toLowerCase().includes("limit") || errorMessage.includes("429")) {
      throw new Error("Gemini API quota exceeded. Please check your billing or try again later, or switch to 'LITE' mode.");
    }
    
    // For other errors (like invalid API key), rethrow so the UI can show the error
    throw error;
  }
}

export async function removeBackground(base64Image: string, mimeType: string = "image/png") {
  if (useLocalAi) {
    console.log("Using Local AI Engine for background removal...");
    return await localRemoveBackground(base64Image);
  }

  const apiKey = getUserApiKey() || process.env.GEMINI_API_KEY || "";
  if (!apiKey) {
    throw new Error("No Gemini API key found for Pro background removal. Please add your key in the Profile settings.");
  }
  
  const ai = new GoogleGenAI({ apiKey });
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: {
        parts: [
          {
            text: `[CRITICAL: MANDATORY IMAGE OUTPUT] You are an AI background removal engine.
INPUT: An image.
TASK: Remove the background from the image and return the subject with a transparent-ready background.
RESPONSE RULE: Return ONLY the processed image data. NO TEXT. NO EXPLANATIONS. ONLY THE IMAGE.`
          },
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Image.split(',')[1] || base64Image
            }
          }
        ]
      },
      config: {
        temperature: 0.1,
        topP: 0.8,
        topK: 10
      }
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("Background removal failed");
  } catch (error: any) {
    console.error("Background removal failed:", error);
    
    const errorMessage = error.message || String(error);
    if (errorMessage.toLowerCase().includes("quota") || errorMessage.toLowerCase().includes("limit") || errorMessage.includes("429")) {
      throw new Error("Gemini API quota exceeded during background removal.");
    }
    
    throw error;
  }
}

export async function transformVideo(videoPrompt: string, imageBase64?: string, resolution: '720p' | '1080p' = '720p') {
  // Video generation (Veo) is extremely heavy and cannot run locally in a browser.
  // We will provide a "Local Flipbook" simulation if no key is present.
  const apiKey = getUserApiKey() || (process.env as any).API_KEY || process.env.GEMINI_API_KEY || "";
  
  if (!apiKey) {
    throw new Error("Local Video AI is not supported yet. Please use the 'Free AI Animation' (Flipbook) feature which runs locally on your frames.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  try {
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: videoPrompt,
      image: imageBase64 ? {
        imageBytes: imageBase64.split(',')[1] || imageBase64,
        mimeType: 'image/png',
      } : undefined,
      config: {
        numberOfVideos: 1,
        resolution: resolution,
        aspectRatio: '16:9'
      }
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000));
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) throw new Error("Video generation failed - no download link received");

    const response = await fetch(downloadLink, {
      method: 'GET',
      headers: {
        'x-goog-api-key': apiKey,
      },
    });

    if (!response.ok) {
      const errorText = await response.text();
      if (response.status === 403) {
        throw new Error("API Key issue: Permission Denied (403). Please ensure your selected API key is from a Google Cloud project with billing enabled and has access to Veo.");
      }
      throw new Error(`Failed to fetch generated video: ${response.status} ${response.statusText} - ${errorText}`);
    }

    const blob = await response.blob();
    return URL.createObjectURL(blob);
  } catch (error: any) {
    console.error("Video transformation failed:", error);
    
    const errorMessage = error.message || String(error);
    if (errorMessage.toLowerCase().includes("quota") || errorMessage.toLowerCase().includes("limit") || errorMessage.includes("429")) {
      throw new Error("You have reached your AI Video quota. Please try the 'Free AI Animation' (Flipbook) feature instead, which runs locally on your device.");
    }
    
    throw error;
  }
}
